name: flutter_one_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 网络请求
  dio: ">=3.0.3 <6.0.0"
  # 网络缓存图片(有缓存功能)
  cached_network_image: ">=2.0.0-rc <4.0.0"
  # 图片加载(可定义缩放等功能)
  extended_image: ">=0.6.7 <8.0.0"
  # 事件总线
  event_bus: ">=1.1.0 <3.0.0"
  # 下拉刷新、上拉加载
  flutter_easyrefresh: ^2.0.4
  # 微光效果控件
  shimmer: ">=1.0.1 <3.0.0"
  # 日期选择控件
  flutter_datetime_picker: ^1.2.6
  # HTML加载
  flutter_html: ">=0.11.0 <3.0.0"
  # 网页加载
  webview_flutter: ">=0.3.19+5 <3.0.0"
  # 权限申请
  permission_handler: ">=3.2.2 <11.0.0"
  # 保存图片到相册
  image_downloader: ">=0.19.1 <0.32.0"
  # Toast吐司
  fluttertoast: ">=3.1.3 <9.0.0"
  # 音乐播放
  audioplayers: ">=0.14.0 <4.0.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=0.1.2 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ic_one_normal.png
    - images/ic_one_selected.png
    - images/ic_all_normal.png
    - images/ic_all_selected.png
    - images/ic_me_normal.png
    - images/ic_me_selected.png
    - images/img_all_category_001.png
    - images/img_all_category_002.png
    - images/img_all_category_003.png
    - images/img_all_category_004.png
    - images/img_all_category_005.png
    - images/img_me_avatar.png
    - images/img_me_bg_001.png
    - images/img_me_bg_002.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
